name: Auto-merge Dependabot

on: pull_request

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: eightsleep-pager
    steps:
      - name: Install runner dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends gh
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
